/*
  Warnings:

  - The `skills` column on the `User` table would be dropped and recreated. This will lead to data loss if there is data in the column.

*/
-- CreateEnum
CREATE TYPE "Skill" AS ENUM ('REACT', 'NODE_JS', 'TYPESCRIPT', 'JAVASCRIPT', 'PYTHON', 'JAVA', 'CSHARP', 'CPLUSPLUS', 'RUBY', 'GO', 'PHP', 'SQL', 'NOSQL', 'SYSTEM_DESIGN', 'MICROSERVICES', 'DEVOPS', 'AWS', 'AZURE', 'DOCKER', 'KUBERNETES', 'DATA_SCIENCE', 'MACHINE_LEARNING', 'DEEP_LEARNING', 'COMPUTER_VISION', 'NLP', 'MLOPS', 'BIG_DATA', 'STATISTICS', 'UX', 'UI', 'FIGMA', 'DESIGN_SYSTEMS', 'ACCESSIBILITY', 'PORTFOLIO_REVIEW', 'MOTION_DESIGN', 'PRODUCT_MANAGEMENT', 'AGILE', 'SCRUM', 'USER_RESEARCH', 'MARKET_ANALYSIS', 'BUSINESS_STRATEGY', 'STARTUPS', 'DIGITAL_MARKETING', 'CONTENT_STRATEGY', 'SEO', 'SOCIAL_MEDIA', 'BRANDING', 'GROWTH_HACKING', 'COPYWRITING', 'STORYTELLING', 'INTERVIEW_PREP', 'RESUME_REVIEW', 'CAREER_COACHING', 'PUBLIC_SPEAKING', 'NETWORKING', 'LEADERSHIP', 'TEAM_MANAGEMENT');

-- AlterTable
ALTER TABLE "User" DROP COLUMN "skills",
ADD COLUMN     "skills" "Skill"[];
